### ISSUE TITLE
Only some images works

### ISSUE THREAD

**Issue by Lexumiii** [ItzBlinkzy/prntscraper#3] opened 2021-11-03 13:50 UTC
Hello, 

I got some issues using your tool. 

On some downloads, I am not able to open or see them:
![image](https://user-images.githubusercontent.com/64711939/140071566-36a8c4fd-a669-4592-9919-c65fa2c132d2.png)

As you can see in the Image, only the first, second and last picture is working. (Opening them doesn't work either)

All images are available on the website.

Is there a fix for this issue? 

Greetings Lexumi

**Comment by ItzBlinkzy** [comment] 2021-11-04 17:28
Hey,
I've noticed this bug before and I will try to find a fix for this later this week. Thanks for bringing it to my attention again. 
Also please tell me what version of the program you are using.

**Comment by Lexumiii** [comment] 2021-11-08 19:22
Thank you, did you find a solution by now?

**Comment by Lexumiii** [comment] 2021-11-18 18:16
Sir?

**Comment by ItzBlinkzy** [comment] 2021-11-18 19:13
Sorry, I couldn't find a solution when I briefly checked, I will try again in the coming week or two to fully sort this bug out.

**Comment by yashma052** [comment] 2021-12-02 22:08
Hi.  I just can't install an iPhone on the iSH terminal.  what commands do you need?  and also, please make it so that you can parse a certain link, that is, not from random

**Comment by ItzBlinkzy** [comment] 2021-12-03 17:55
Hello, this program does not work in iSH terminal because there is no way to store the files and view them.

**Comment by yashma052** [comment] 2021-12-04 11:48
I used this parsing github.com/senges/lightshot for 2 years, on an iPhone in the iSH terminal, now it stopped working because prntsc.com added additional symbols for links, before there were 6 of them and now out of 7, I don't know the problem is  how.  but it will work for you too, if you tell me how to run correctly

**Comment by ItzBlinkzy** [comment] 2021-12-04 11:57
I already answered this issue  in -> https://github.com/ItzBlinkzy/prntscraper/issues/1

**Comment by yashma052** [comment] 2021-12-04 16:39
> I already answered this issue  in -> https://github.com/ItzBlinkzy/prntscraper/issues/1

Great.  I installed it.  but I don’t know which command to run, I tried python3 scraper.py but it doesn’t work.  How is it possible that you can selectively parse the link?

**Comment by ItzBlinkzy** [comment] 2021-12-08 15:43
You need to run `python` in the shell and import the library, then use the methods to collect images, examples in [README.md](https://github.com/ItzBlinkzy/prntscraper/blob/master/README.md)

**Comment by Lexumiii** [comment] 2021-12-10 23:35
> Sorry, I couldn't find a solution when I briefly checked, I will try again in the coming week or two to fully sort this bug out.

Could you find any solution by now?

**Comment by ItzBlinkzy** [comment] 2021-12-14 20:52
> > Sorry, I couldn't find a solution when I briefly checked, I will try again in the coming week or two to fully sort this bug out.
> 
> Could you find any solution by now?

Finally, fixed it, was an issue with failing requests, I will be publishing a new version later today.

**Comment by ItzBlinkzy** [comment] 2021-12-14 21:06
New version published.
https://pypi.org/project/prntscraper/2.5.5/

#### Note: Downloading images may be slightly slower now because of this bug being fixed but that now results on a much higher accuracy of downloading an image that isn't broken or deleted.

(Feel free to leave any issues with this update, and I'll close this issue in a few days if everything is working fine.)

**Comment by Lexumiii** [comment] 2021-12-30 07:14
Cool :D. 
Thanks for fixing it 👍

I'm going to test it now and keep you updated if I find any issues.

**Closed as completed** 2022-01-02 21:04 UTC
Labels: bug
